translations/ui-erm-comparisons/ar.json, translations/ui-erm-comparisons/ca.json, translations/ui-erm-comparisons/da.json, translations/ui-erm-comparisons/de.json, translations/ui-erm-comparisons/en_GB.json, translations/ui-erm-comparisons/en_SE.json, translations/ui-erm-comparisons/en_US.json, translations/ui-erm-comparisons/es.json, translations/ui-erm-comparisons/es_419.json, translations/ui-erm-comparisons/es_ES.json, translations/ui-erm-comparisons/fr.json, translations/ui-erm-comparisons/fr_FR.json, translations/ui-erm-comparisons/he.json, translations/ui-erm-comparisons/hu.json, translations/ui-erm-comparisons/it_IT.json, translations/ui-erm-comparisons/ja.json, translations/ui-erm-comparisons/pt_BR.json, translations/ui-erm-comparisons/pt_PT.json, translations/ui-erm-comparisons/ru.json, translations/ui-erm-comparisons/ur.json, translations/ui-erm-comparisons/zh_CN.json, translations/ui-erm-comparisons/zh_TW.json
=> Update translation strings as of 20200804T150835

translations/ui-erm-comparisons/fr_FR.json, translations/ui-erm-comparisons/zh_CN.json
=> Update translation strings as of 20200824T140725

translations/ui-erm-comparisons/pt_BR.json
=> Update translation strings as of 20200922T125348

translations/ui-erm-comparisons/zh_CN.json
=> Update translation strings as of 20200928T202231

translations/ui-erm-comparisons/de.json
=> Update translation strings as of 20201005T202004

translations/ui-erm-comparisons/it_IT.json
=> Update translation strings as of 20201111T142927

src/components/ComparisonFilters/ComparisonFilters.js, src/routes/ComparisonsRoute.js, test/bigtest/network/factories/comparison.js
=> add filterKeys to ComparisonsRoute, filter by value, refs ERM-1553

src/index.js, translations/ui-erm-comparisons/en.json
* use KeyboardShortcutsModal and NavList component in App
=> ERM-1737 display the keyboard shortcuts modal

package.json, test/bigtest/tests/application-test.js
Bumped dependency on eslint-config-stripes to 6.0.0
ERM-1971
=> chore: eslint-config-stripes

package.json, src/components/views/ComparisonReport.js, src/components/views/ComparisonReportList.js, test/bigtest/.eslintrc.js, test/bigtest/tests/application-test.js, test/bigtest/tests/comparison-point-field-array-test.js
* add autosize prop to MCL in ComparisonReportList
* add height prop to paneProps in ComparisonReport
=> ERM-1980 Non-scrolling column headings in ERM Comparisons report view

CHANGELOG.md, package.json
Bumped version to 4.2.0, added changelog section
=> chore: Version bump

CHANGELOG.md, package.json
Release 4.1.3 failing tests on CI, fixed config
=> test: Test fix

CHANGELOG.md, package.json
Updated dependencies and changelog ready for release
ERM-2031
=> chore: Release 4.2.0

CHANGELOG.md, package.json
Snafu with the git tag, releasing with a bump to 4.2.1
ERM-2027
=> chore: Release 4.2.1

package.json, src/components/ComparisonPointFieldArray/ComparisonPointFieldArray.js
* convert ComparisonPointFieldArray to functional component
* switch to useKiwtFieldArray in ComparisonPointFieldArray
* add stripes-kint-components to package.json dependencies
=> ERM-2234 Replace withKiwtFieldArray with useKiwtFieldArray

package.json
* add stripes-erm-components as peer and dev dependency
* remove it from 'dependencies'
=> ERM-2320 stripes-erm-components should be a peer

.eslintrc, src/components/ComparisonPointFieldArray/ComparisonPointFieldArray.js, test/bigtest/helpers/translationsProperties.js
* fix name property
* fix .eslintrc
* fix lint warning
=> ERM-2337 Error on attempting to create new ERM comparison

package.json, src/components/ComparisonFilters/ComparisonFilters.test.js, src/components/ComparisonFilters/ComparisonPointFilter.js, src/components/ComparisonFilters/ComparisonPointFilter.test.js
* Add test coverage for ComparisonFilters
* Add test coverage for ComparisonPointFilter
* Refactor ComparisonPointFilter to a functional component
=> ERM-1307, Add test coverage for ComparisonFilters

__mocks__/@folio/stripes-erm-components.js, __mocks__/@folio/stripes/components.js, __mocks__/@folio/stripes/core.js, __mocks__/@folio/stripes/smart-components.js, __mocks__/@k-int/stripes-kint-components.js, __mocks__/currency-codes/data.js, __mocks__/react-query.js, __mocks__/react-router-dom.js, __mocks__/stripes-config.js, jest.config.js, package.json, src/components/ComparisonFilters/ComparisonFilters.test.js, src/components/ComparisonFilters/ComparisonPointFilter.test.js, test/jest/helpers/translationsProperties.js
Moved all jest tests over to manual mocks and imports from stripes-erm-testing
=> test: erm-testing

src/components/ComparisonPointFieldArray/AgreementField.js, src/components/ComparisonPointFieldArray/AgreementField.test.js, src/components/ComparisonPointFieldArray/ComparisonPointField.test.js, src/components/ComparisonPointFieldArray/ComparisonPointFieldArray.test.js, src/components/ComparisonPointFieldArray/PackageField.js, src/components/ComparisonPointFieldArray/PackageField.test.js, src/components/ComparisonPointFieldArray/testResources.js, test/bigtest/helpers/translationsProperties.js, test/jest/helpers/translationsProperties.js
Fixed test warnings and tweaked tests to better reflect reality -- rendering fieldArrays inside a fieldArray etc. Also added mock for Registry as a quick example of how we can do that
=> test: Test warnings

src/routes/ComparisonViewRoute/ComparisonViewRoute.js
feat: downloadBlob
Make use of new options params for downloadBlob
ERM-2467
=> ERM-2467: Change export file name and file extension

src/components/ComparisonFilters/ComparisonFilters.js, src/components/ComparisonFilters/ComparisonFilters.test.js, src/components/ComparisonFilters/useComparisonPointLookup.js, src/components/views/Comparisons/Comparisons.test.js, src/constants/endpoints.js, src/routes/ComparisonsRoute/ComparisonsRoute.test.js
* converted to functional component
* fixed reset filters
=> ERM-2555, Clicking "Reset all" in ERM Comparison search does not clear comparison point names

.github/workflows/build-npm-release.yml, CHANGELOG.md, package.json
Updated CHANGELOG, ensured dependencies are up to date
ERM-2505
=> chore: Release 5.0.0

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml
Updated github workflows to allow use of multiple cores while running jest tests
=> build: github workflows

src/components/views/ComparisonReportList/ComparisonReportList.js, translations/ui-erm-comparisons/en.json
* add load message on top of ComparisonReportList
* move load button out of MCL
* place load buttons on top and bottom
* place scrollable MCL between top and bottom
=> ERM-1061 Comparison report - display message indicating there are more records to load

package.json, src/components/views/Comparisons/Comparisons.test.js
Added okapi interface dependency on new erm interface 6.0
refs ERM-2641
=> build: erm 6.0

CHANGELOG.md, package.json, src/routes/ComparisonReportViewRoute/ComparisonReportViewRoute.test.js
Refs [ERM-3028](https://issues.folio.org/browse/ERM-3028)
=> STRIPES-868 BREAKING bump react-intl to v6

CHANGELOG.md
=> ERM-3110 ui-erm-comparisons release

GUIDANCE.md, LICENSE
Updated license and added guidance.md file
=> ERM-3377: Update module license and guidance

CHANGELOG.md, package.json
Updated dependencies and updated CHANGELOG.md section to reflect release changes
ERM-3414
=> chore: Release 8.0.0

CHANGELOG.md, package.json
Bumped version to 8.1.0 and added new CHANGELOG.md section
=> chore: Post release 8.0.0

src/components/ComparisonPointFieldArray/ComparisonPointFieldArray.js
Fixed default value fromat from fixed date format to Iso string
ERM-3715
=> ERM-3715: ERM Comparison jobs submitted with date in incorrect format
